name: project-test
on: push
jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup-NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
          cache: npm
    - run: make lint
    - run: make test